[package]
name = "plasmid-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plasmid = { path = "../libplasmid" }
clap = { version = "3.1", features = ["derive", "unicode"] }
pad = "0.1.6"