on: [push, pull_request]

name: CI

jobs:
  build_windows:
    name: Build Plasmid Designer for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Create build directory
        run: mkdir ./plasmid-gui/build
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: tauri
          args: build
