on: [push, pull_request]

name: CI

jobs:
  test_lib:
    name: Test libPlasmid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p plasmid
  test_cli:
    name: Test Plasmid CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p plasmid-cli
